decisionhub/decisionhub.github.io

public/index.html, src/components/about.jsx
I made 3 changes for SEO. First, I added the doctype to index.html. I am aware that we were using the default html so this isn't necessary but it good to have it for SEO. Second, I updated the meta description to include all 5 keywords identified by the SEO site. Third, I added text to the alt field of the 'about' image. I missed this one last time but I believe this is the last one I need to do. Let me know if you would prefer different text in this field.
=> add doctype and update meta description and add alt field

public/css/bootstrap.css, public/css/style.css, public/index.html, src/components/about.jsx, src/components/features.jsx, src/components/services.jsx
This will make the webpage look proportional on mobile but there is a horizonal scroll.
=> mobile support

public/css/style.css, src/App.jsx, src/components/about.jsx, src/components/about2.jsx, src/components/ourgoal.jsx, src/data/data.json
Wanted to get your thoughts on what I have so far. I removed the image and split the about section into 2 components and set them side by side. I still want to make this look nicer because right now it's not much of an improvement over what we had before and I haven't added the new text yet but I want to make sure what I'm doing is ok so far.
=> initial about section changes

src/components/contact.jsx, src/components/navigation.jsx
=> Dynamic year in footer

public/css/style.css, src/components/contact.jsx
=> Add book meeting button

src/components/features.jsx
=> Add product demo to website

src/components/contact.jsx, src/components/navigation.jsx, src/components/team.jsx
It is good to add rel attribute along with a `target="_blank"` based on this article: https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/ (Sherry pointed it out to me for website repo)
=> Add rel to external links

src/data/data.json
=> Add UWWR Testimonial Video

public/css/style.css, src/components/contact.jsx, src/data/data.json
=> Add medium link to socials in footer

public/css/bootstrap.css, src/components/features.jsx
iphone XR 1 column for features:
iphone SE navbar dropdown fits:
=> Fix 2 UI bugs

package-lock.json, package.json, public/css/style.css, src/App.jsx, src/components/features.jsx, src/components/navigation.jsx
Loom video demo: https://www.loom.com/share/ff58ffc2378e4ba78df0015465cf3e88
Todo items:
=> Refactor website into subpages

src/App.jsx, src/components/navigation.jsx, src/components/ourgoal.jsx
=> Reword About to Our Mission

src/components/header.jsx, src/data/data.json
=> Autoplay videos on page load

README.md
=> Update About DecisionHub section in README

README.md
=> Remove Usage Stats section in README

public/index.html, src/data/data.json
=> Rebrand verbiage to application review platform

public/css/style.css, src/components/header.jsx, src/components/navigation.jsx, src/data/data.json
Also did some small css changes
close #65
=> Book CTA at top of website

public/index.html
close #95 
see here: https://knowledge.hubspot.com/reports/install-the-hubspot-tracking-code
=> Add hubspot tracking

src/components/usecasestatement.jsx, src/data/data.json
=> Update use case + remove autoplay

src/components/navigation.jsx
Before:
Top nav looks like this now:
=> Remove signup button
